version: 2
jobs:
  buildlinuxclang:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Build with Clang on Linux
          command: sh ci/linux.sh clang_build
  buildlinuxgcc:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Build Linux with gcc
          command: sh ci/linux.sh gcc_build
  buildmac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build OSX
          command: sh ci/osx.sh build
  buildmacios:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Build iOS
          command: BUILD_IOS=1 sh ci/osx.sh build

workflows:
  version: 2
  build:
    jobs:
      - buildlinuxclang
      - buildlinuxgcc
      - buildmac
      - buildmacios
