version: 2
jobs:
  buildlinuxclang:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build with Clang on Linux
          command: sh ci/linux.sh build
  buildmac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build OSX
          command: sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFDriver.zip
          destination: libNFDriver.zip

workflows:
  version: 2
  build:
    jobs:
      - buildlinuxclang
      - buildmac
